### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by taomaker** [hermanschaaf/mafan#13]
Problem installing wsgiref using pip, might be a problem of python3 compatibility?

``` shell
  Downloading wsgiref-0.1.2.zip
  Running setup.py (path:/deleted/build/wsgiref/setup.py) egg_info for package wsgiref
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/deleted/build/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/deleted/build/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
```

**Comment by astromme** [comment]
This is the same as Issue #9. Probably should be deduped.

**Comment by hermanschaaf** [comment]
Closed by https://github.com/hermanschaaf/mafan/pull/17. I also updated the version on pypi to 0.3.0.
